layout:
  margin:
    left: '2cm'
    top: '1cm'
    right: '2cm'
    bottom: '1cm'
  header: '<div id="template"><div class="all"><span class="title">{} - {}</span></div></div>'
  footer: '<div id="template"><div class="left">created: {}</div></div>'
hide_elements:
  - '.navbar'
  - '.sidebar'
  - '.page-nav'
  - 'iframe'
  - 'video'
